local keymaps = {
  -- { "<leader>,", function() require('fzf-lua').buffers() end, desc = "Buffers", },
  -- { "<leader>/", function() require('fzf-lua').live_grep() end, desc = "Grep", },
  { "<leader>:", function() require('fzf-lua').command_history() end, desc = "Command History", },
  { "<leader><space>", function() require('fzf-lua').files() end, desc = "Find Files", },
  { "<leader>/", function() require('fzf-lua').buffers() end, desc = "Buffers", },
  { "<leader>fc", function() require('fzf-lua').files({ cwd = vim.fn.stdpath("config") }) end, desc = "Find Config File", },
  { "<leader>sf", function() require('fzf-lua').files() end, desc = "Find Files", },
  { "<leader>fg", function() require('fzf-lua').git_files() end, desc = "Find Git Files", },
  { "<leader>fr", function() require('fzf-lua').oldfiles() end, desc = "Recent", },
  { "<leader>gc", function() require('fzf-lua').git_commits() end, desc = "Git Log", },
  { "<leader>gs", function() require('fzf-lua').git_status() end, desc = "Git Status", },
  { "<leader>sb", function() require('fzf-lua').lines() end, desc = "Buffer Lines", },
  { "<leader>sB", function() require('fzf-lua').grep_buffers() end, desc = "Grep Open Buffers", },
  { "<leader>sg", function() require('fzf-lua').live_grep() end, desc = "Grep", },
  { "<leader>sw", function() require('fzf-lua').grep_cword() end, desc = "Visual selection or word", mode = { "n", "x" }, },
  { "<leader>sW", function() require('fzf-lua').grep_cWORD() end, desc = "Visual selection or word", mode = { "n", "x" }, },
  { '<leader>s"', function() require('fzf-lua').registers() end, desc = "Registers", },
  { "<leader>sa", function() require('fzf-lua').autocmds() end, desc = "Autocmds", },
  { "<leader>sc", function() require('fzf-lua').command_history() end, desc = "Command History", },
  { "<leader>sC", function() require('fzf-lua').commands() end, desc = "Commands", },
  { "<leader>sd", function() require('fzf-lua').diagnostics() end, desc = "Diagnostics", },
  { "<leader>sh", function() require('fzf-lua').help_tags() end, desc = "Help Pages", },
  { "<leader>sH", function() require('fzf-lua').highlights() end, desc = "Highlights", },
  { "<leader>sj", function() require('fzf-lua').jumps() end, desc = "Jumps", },
  { "<leader>sk", function() require('fzf-lua').keymaps() end, desc = "Keymaps", },
  { "<leader>sl", function() require('fzf-lua').loclist() end, desc = "Location List", },
  { "<leader>sM", function() require('fzf-lua').man_pages() end, desc = "Man Pages", },
  { "<leader>sm", function() require('fzf-lua').marks() end, desc = "Marks", },
  { "<leader>sR", function() require('fzf-lua').resume() end, desc = "Resume", },
  { "<leader>sq", function() require('fzf-lua').quickfix() end, desc = "Quickfix List", },
  { "<leader>uC", function() require('fzf-lua').colorschemes() end, desc = "Colorschemes", },
  { "<leader>qp", function() require('fzf-lua').projects() end, desc = "Projects", },
  { "gd", function() require('fzf-lua').lsp_definitions() end, desc = "Goto Definition", },
  { "<leader>ca", function() require('fzf-lua').lsp_code_actions() end, desc = "Code Actions", },
  { "<leader>rr", function() require('fzf-lua').lsp_references() end, nowait = true, desc = "References", },
  { "<leader>gI", function() require('fzf-lua').lsp_implementations() end, desc = "Goto Implementation", },
  { "<leader>gy", function() require('fzf-lua').lsp_typedefs() end, desc = "Goto T[y]pe Definition", },
  { "<leader>ss", function() require('fzf-lua').lsp_document_symbols() end, desc = "LSP Symbols", },
}

return keymaps
