local picker_opts = {
	enabled = true,
	animate = false,
	prompt = " ",
	sources = {
		files = {
			title = " files 📑 ",
			finder = "files",
			format = "file",
			show_empty = true,
			supports_live = true,
		},
		buffers = { title = " buffers 📝 " },
		help = { title = " help 💡 " },
		git_status = { title = " git status  " },
		lsp_references = {
			debounce = 50,
			auto_confirm = false,
		},
	},
	layout = {
		cycle = true,
		preset = "default",
	},
	matcher = {
		fuzzy = true,
		smartcase = true,
		ignorecase = true,
		sort_empty = false,
		filename_bonus = true,
		file_pos = true,
		cwd_bonus = true,
		frecency = true,
	},
	ui_select = true,
	sort = {
		fields = { "score:desc", "#text", "idx" },
	},
	win = {
		input = {
			keys = {
				["<C-c>"] = { "close", mode = "i" },
				["<Esc>"] = { "close", mode = { "n", "i" } },
				["<C-y>"] = { "confirm", mode = { "n", "i" } },
				["G"] = "list_bottom",
				["gg"] = "list_top",
				["<C-j>"] = { "list_down", mode = { "i", "n" } },
				["<C-k>"] = { "list_up", mode = { "i", "n" } },
				["/"] = "toggle_focus",
				["?"] = "toggle_help",
				["<a-d>"] = { "inspect", mode = { "n", "i" } },
				["<c-a>"] = { "select_all", mode = { "n", "i" } },
				["<a-m>"] = { "toggle_maximize", mode = { "i", "n" } },
				["<a-p>"] = { "toggle_preview", mode = { "i", "n" } },
				["<a-w>"] = { "cycle_win", mode = { "i", "n" } },
				-- ["<C-w>"] = { "<c-s-w>", mode = { "i" }, desc = "delete word" },
				-- ["<C-w>"] = "<c-s-w>",
				["<C-Up>"] = { "history_back", mode = { "i", "n" } },
				["<C-Down>"] = { "history_forward", mode = { "i", "n" } },
				["<Tab>"] = { "select_and_next", mode = { "i", "n" } },
				["<S-Tab>"] = { "select_and_prev", mode = { "i", "n" } },
				["<c-n>"] = { "list_down", mode = { "i", "n" } },
				["<c-p>"] = { "list_up", mode = { "i", "n" } },
				["<c-l>"] = { "preview_scroll_left", mode = { "i", "n" } },
				["<c-h>"] = { "preview_scroll_right", mode = { "i", "n" } },
				["<c-b>"] = { "preview_scroll_up", mode = { "i", "n" } },
				["<c-d>"] = { "list_scroll_down", mode = { "i", "n" } },
				["<c-f>"] = { "preview_scroll_down", mode = { "i", "n" } },
				["<c-g>"] = { "toggle_live", mode = { "i", "n" } },
				["<c-u>"] = { "list_scroll_up", mode = { "i", "n" } },
				["<c-v>"] = { "edit_vsplit", mode = { "i", "n" } },
				["<c-s>"] = { "edit_split", mode = { "i", "n" } },
				["<c-q>"] = { "qflist", mode = { "i", "n" } },
				["<a-i>"] = { "toggle_ignored", mode = { "i", "n" } },
				["<a-h>"] = { "toggle_hidden", mode = { "i", "n" } },
				["<a-f>"] = { "toggle_follow", mode = { "i", "n" } },
			},
		},
		list = {
			border = "rounded",
			keys = {
				["<CR>"] = "confirm",
				["gg"] = "list_top",
				["G"] = "list_bottom",
				["<C-j>"] = { "list_down", mode = { "i", "n" } },
				["<C-k>"] = { "list_up", mode = { "i", "n" } },
				["<Tab>"] = "select_and_next",
				["<S-Tab>"] = "select_and_prev",
				["<a-d>"] = "inspect",
				["<c-d>"] = "list_scroll_down",
				["<c-u>"] = "list_scroll_up",
				["zt"] = "list_scroll_top",
				["zb"] = "list_scroll_bottom",
				["zz"] = "list_scroll_center",
				["/"] = "toggle_focus",
				["<c-a>"] = "select_all",
				["<c-f>"] = "preview_scroll_down",
				["<c-b>"] = "preview_scroll_up",
				["<c-l>"] = "preview_scroll_right",
				["<c-h>"] = "preview_scroll_left",
				["<c-v>"] = "edit_vsplit",
				["<c-s>"] = "edit_split",
				["<c-n>"] = "list_down",
				["<c-p>"] = "list_up",
				["<a-w>"] = "cycle_win",
				["<Esc>"] = "close",
			},
			wo = {
				conceallevel = 2,
				concealcursor = "nvc",
			},
		},
		preview = {
			border = "rounded",
			keys = {
				["<Esc>"] = "close",
				["q"] = "close",
				["i"] = "focus_input",
				["<C-b>"] = "list_scroll_wheel_down",
				["<C-f>"] = "list_scroll_wheel_up",
				["<a-w>"] = "cycle_win",
			},
		},
	},
	icons = {
		files = { enabled = true },
		keymaps = { nowait = "󰓅 " },
		indent = { vertical = "│ ", middle = "├╴", last = "└╴" },
		ui = {
			live = "󰐰 ",
			hidden = "h",
			ignored = "i",
			follow = "f",
			unselected = "○ ",
			selected = " ",
		},
		kinds = {
			Array = " ",
			Boolean = "󰨙 ",
			Class = " ",
			Color = " ",
			Constant = "󰏿 ",
			Constructor = " ",
			Enum = " ",
			EnumMember = " ",
			Event = " ",
			Field = " ",
			File = " ",
			Folder = " ",
			Function = "󰊕 ",
			Interface = " ",
			Key = " ",
			Keyword = " ",
			Method = "󰊕 ",
			Module = " ",
			Namespace = "󰦮 ",
			Null = " ",
			Number = "󰎠 ",
			Object = " ",
			Operator = " ",
			Package = " ",
			Property = " ",
			Reference = " ",
			Snippet = "󱄽 ",
			String = " ",
			Struct = "󰆼 ",
			Text = " ",
			TypeParameter = " ",
			Unit = " ",
			Unknown = " ",
			Value = " ",
			Variable = "󰀫 ",
		},
	},
}
return picker_opts
